# Logging
quarkus.log.category."com.redhat.demos.thoughts".level=DEBUG

#Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.bind-parameters=true

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
