# Logging
quarkus.log.category."com.redhat.demos".level=DEBUG

# Kafka configuration
mp.messaging.incoming.thoughts-in.auto.offset.reset=earliest
mp.messaging.incoming.thoughts-in.topic=thoughts-created
mp.messaging.outgoing.thoughts-out.topic=thoughts-evaluated

# Ollama / IBM Granite
quarkus.langchain4j.ollama.chat-model.model-name=granite3.2:8b
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.timeout=60s

